import * as React from "react";
import { Text, Hr } from "@react-email/components";
import { BaseEmail, brand, sharedStyles } from "./base.js";

export type SignalProps = {
  sport: string;
  matchup: string;
  market: string;
  edge: string;
  price: string;
  startTime?: string;
  modelPct?: number;
  marketPct?: number;
  margin?: number | null;
  appUrl: string;
  unsubscribeUrl?: string;
};

export default function SignalEmail({
  market = "Celtics -4.5",
  edge = "+5.8%",
  price = "DraftKings",
  startTime,
  modelPct,
  marketPct,
  margin,
  appUrl = "https://app.sharppicks.ai",
  unsubscribeUrl,
}: SignalProps) {
  const hasMetrics = modelPct != null && marketPct != null;
  return (
    <BaseEmail
      preview={`Signal generated — ${market}`}
      label="SIGNAL GENERATED"
      ctaText="VIEW FULL ANALYSIS"
      ctaUrl={appUrl}
      finePrint="This signal was generated by the SharpPicks model. Past performance does not guarantee future results."
      footerNote="SharpPicks — Discipline is the product."
      unsubscribeUrl={unsubscribeUrl}
      appUrl={appUrl}
    >
      {startTime ? (
        <Text style={{ ...sharedStyles.copy, margin: "0 0 20px", fontSize: "13px", color: brand.label }}>
          {startTime}
        </Text>
      ) : null}
      <Text style={{ ...sharedStyles.heading, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "22px", fontWeight: 700, color: brand.text, margin: "0 0 8px" }}>
        {market}
      </Text>
      <Text style={{ fontFamily: "Arial, Helvetica, sans-serif", fontSize: "18px", fontWeight: 700, color: brand.green, margin: "0 0 20px" }}>
        Edge: {edge}
      </Text>
      {hasMetrics ? (
        <>
          <Text style={{ ...sharedStyles.rowValue, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "15px", color: brand.text, padding: "4px 0" }}>
            Model: {modelPct}%
          </Text>
          <Text style={{ ...sharedStyles.rowValue, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "15px", color: brand.text, padding: "4px 0" }}>
            Market: {marketPct}%
          </Text>
          <Hr style={{ border: "none", borderTop: `1px solid ${brand.line}`, margin: "0 0 16px" }} />
          <Text style={{ ...sharedStyles.rowLabel, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "13px", color: brand.textMuted, padding: "4px 0" }}>
            Calibrated Edge: {edge}
          </Text>
          {margin != null ? (
            <Text style={{ ...sharedStyles.rowLabel, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "13px", color: brand.textMuted, padding: "4px 0" }}>
              Margin Projection: {margin > 0 ? "+" : ""}{margin}
            </Text>
          ) : null}
          <Text style={{ ...sharedStyles.rowLabel, fontFamily: "Arial, Helvetica, sans-serif", fontSize: "13px", color: brand.textMuted, padding: "4px 0" }}>
            Sportsbook: {price}
          </Text>
        </>
      ) : null}
    </BaseEmail>
  );
}
